Views/Controllers/AdminDashboardController.cs
using Entities.Models;
using Entities.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Views.Controllers.BaseControllers;

namespace Views.Controllers
{
    public class AdminDashboardController : BaseAdminController
    {
        // GET: AdminDashboardController
        public async Task<ActionResult> Index(string message, int? startIndex)
        {
            var company = await _companyRepository.GetCompanyWithPostsAsync(CurrentCompanyId);
            var posts = company.Posts != null ? company.Posts.ToList() : new List<Post>();

            int currentIndex = startIndex ?? 0;
            int currentPage = 8;

            posts = posts.OrderByDescending(p => p.PostDate).ToList();

            var page = posts.Skip(currentIndex).Take(currentPage);

            DashBoardViewModel model = new DashBoardViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentCompany, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel
                Message = message, //BaseViewModel

                CurrentIndex = currentIndex, //Paged
                CurrentPage = currentPage, //Paged
                MaxIndex = posts.Count(), //Paged

                Posts = page.ToList()
            };


            return View(model);
        }

        public async Task<JsonResult> GetPosts()
        {
            var company = await _companyRepository.GetCompanyWithPostsAsync(CurrentCompanyId);
            var posts = company.Posts != null ? company.Posts.ToList() : new List<Post>();
            posts = posts.OrderByDescending(p => p.PostDate).ToList();
            return new JsonResult { Data = posts, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }


        [HttpPost]
        public async Task<JsonResult> Submit(Post e)
        {
            var status = false;
            IFormatProvider culture = new CultureInfo("en-US", true);
            Post post = new Post()
            {
                Content = e.Content,
                PostDate = DateTime.Now
            };

            if (ModelState.IsValid)
            {
                status = await _companyRepository.CreateCompanyPostAsync(post, CurrentCompanyId);
            }

            return new JsonResult { Data = new { status = status } };
        }


        [HttpPost]
        public async Task<JsonResult> Update(Post e)
        {
            var status = false;
            Post post = new Post()
            {
                Content = e.Content,
                PostDate = DateTime.Now,
                PostId = e.PostId,
                CompanyId = CurrentCompanyId
            };



            if (ModelState.IsValid)
            {
                status = await _companyRepository.UpdateCompanyPostAsync(post);
            }

            return new JsonResult { Data = new { status = status } };
        }


        public async Task<ActionResult> Delete(Post post)
        {
            var status = false;
            status = await _companyRepository.DeleteCompanyPostAsync(post.PostId);
            return new JsonResult { Data = new { status = status } };
        }

    }
}

Views/Controllers/AdminEventController.cs
using Entities.AdminViewModels;
using Entities.EmployeeViewModels;
using Entities.UtilityModels;
using Entities.Models;
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Views.Controllers.BaseControllers;
using System.Collections.Generic;

namespace Views.Controllers
{
    public class AdminEventController : BaseAdminController
    {
        // GET: Event
        public ActionResult Index(string message)
        {
            var employeeUsers = EmployeeManager.Users.Where(u => u.CompanyId == CurrentCompanyId).ToList() ?? new List<EmployeeUser>();

            AdminIndexViewModel model = new AdminIndexViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                Message = message, //BaseViewModel
                LoggedUser = CurrentUser, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel

                Employees = employeeUsers
            };
            return View(model);
        }

        public async Task<JsonResult> GetEvents()
        {
            var events = await _companyRepository.GetCompanyEventsAsync(CurrentCompanyId);

            return new JsonResult { Data = events, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        public async Task<JsonResult> SaveEvent(EmployeeEventViewModel e)
        {
            var status = false;
            IFormatProvider culture = new CultureInfo("en-US", true);

            EmployeeEvent eve = new EmployeeEvent()
            {
                CompanyID = CurrentCompanyId,
                Username = e.Username,
                Overtime = e.Overtime ?? 0,
                Start = DateTime.ParseExact(e.Start, "dd/MM/yyyy HH:mm tt", culture),
                End = DateTime.ParseExact(e.End, "dd/MM/yyyy HH:mm tt", culture),
                Description = e.Description ?? "No description",
                Color = e.Color,
                Status = StatusColor.MapColorToStatus(e.Color),
                IsFullDay = e.IsFullDay,
                EventID = e.EventID
            };

            if (ModelState.IsValid)
            {
                status = await _employeeRepository.CreateEmployeeEventAsync(eve);
            }

            return new JsonResult { Data = new { status = status } };
        }

        [HttpPost]
        public async Task<JsonResult> DeleteEvent(int eventID)
        {
            await _employeeRepository.DeleteEmployeeEventAsync(eventID);

            return new JsonResult { Data = new { status = true } };
        }
    }
}

Views/Controllers/AdminRequestController.cs
using Entities.Models;
using Entities.ViewModels;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Views.Controllers.BaseControllers;

namespace Views.Controllers
{
    public class AdminRequestController : BaseAdminController
    {
        // GET: AdminRequest
        public async Task<ActionResult> Index(string message, int? startIndex)
        {
            int currentIndex = startIndex ?? 0;
            int currentPage = 7;

            var employees = await _employeeRepository.GetEmployeesWithRequestsAsync(CurrentCompanyId);
            var request = employees.SelectMany(x => x.Requests).OrderByDescending(r => r.RequestDate);

            var page = request.Skip(currentIndex).Take(currentPage);

            RequestViewModel model = new RequestViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentCompany, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel
                Message = message, //BaseViewModel

                CurrentIndex = currentIndex, //Paged
                CurrentPage = currentPage, //Paged
                MaxIndex = request.Count(), //Paged

                Requests = page
            };

            return View(model);
        }

        [HttpPost]
        public async Task<JsonResult> Submit(Request e)
        {            
            var status = false;
            IFormatProvider culture = new CultureInfo("en-US", true);

            Request req = new Request()
            {
                Username = e.Username,
                RequestId = e.RequestId,
                AskRequest = e.AskRequest,
                Response = e.Response,
            };

            

            if (ModelState.IsValid)
            {
                status = await _employeeRepository.CreateEmployeeResponseRequestAsync(req);

            }

            return new JsonResult { Data = new { status = status } };
        }
    }
}

Views/Controllers/AdminStatisticsController.cs
using Entities.AdminViewModels;
using Repositories.Services;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Views.Controllers.BaseControllers;

namespace Views.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class AdminStatisticsController : BaseAdminController
    {
        // GET: Statistics
        public ActionResult Index(string message)
        {
            AdminStatisticsViewModel model = new AdminStatisticsViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentUser, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel
                Message = message, //BaseViewModel
            };

            return View(model);
        }

        public ActionResult CompanyStatistics(string message)
        {
            AdminStatisticsViewModel model = new AdminStatisticsViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentUser, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel
                Message = message, //BaseViewModel
            };

            return View(model);
        }

        public async Task<ActionResult> EmployeeStatistics(string message)
        {
            var employees = await _employeeRepository.GetEmployeesAsync(CurrentCompanyId);

            AdminStatisticsViewModel model = new AdminStatisticsViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentUser, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel
                Message = message, //BaseViewModel

                EmployeeNames = employees.ToList()
            };

            return View(model);
        }

        public async Task<JsonResult> MonthlyPayment(string month, string year)
        {
            int currentMonth = int.TryParse(month, out int result) ? result : DateTime.Now.Month;
            int currentYear = int.TryParse(year, out result) ? result : DateTime.Now.Year;

            StatisticsService statistics = new StatisticsService(_employeeRepository);
            var model = await statistics.MonthlyPayment(CurrentCompanyId, currentMonth, currentYear);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> CurrentYearPayments()
        {
            StatisticsService statistics = new StatisticsService(_employeeRepository);
            var model = await statistics.YearPayments(CurrentCompanyId);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> EmployeeSalary(string username)
        {
            StatisticsService statistics = new StatisticsService(_employeeRepository);
            var model = await statistics.EmployeeSalary(username);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> EmployeeAttendance(string username, string month)
        {
            int currentMonth = int.TryParse(month, out int result) ? result : DateTime.Now.Month;

            StatisticsService statistics = new StatisticsService(_employeeRepository);
            var model = await statistics.EmployeeAttendance(username, currentMonth);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> CompanyEmployeesSalaries()
        {
            StatisticsService statistics = new StatisticsService(_employeeRepository);
            var model = await statistics.CompanyEmployeesSalaries(CurrentCompanyId);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public async Task<JsonResult> CompanyAttendance(string month)
        {
            int currentMonth = int.TryParse(month, out int result) ? result : DateTime.Now.Month;

            StatisticsService statistics = new StatisticsService(_employeeRepository);
            var model = await statistics.CompanyAttendance(CurrentCompanyId, currentMonth);

            return Json(model, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/Controllers/EmployeeController.cs
using Entities.EmployeeViewModels;
using Strategy.PaymentStrategy;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Views.Controllers.BaseControllers;

namespace Views.Controllers
{
    public class EmployeeController : BaseEmployeeController
    {
        // GET: Employee
        public async Task<ActionResult> Index()
        {
            var employee = await _employeeRepository.GetEmployeeWithEventsAsync(CurrentUser);
            var todayEvent = await _employeeRepository.GetEmployeeEventByDayAsync(CurrentUser, DateTime.Now.Day, DateTime.Now.Month);
            var tomorrowEvent = await _employeeRepository.GetEmployeeEventByDayAsync(CurrentUser, DateTime.Now.Day + 1, DateTime.Now.Month);

            var strategy = new PaymentStrategy();
            strategy.SetPaymentStrategy(employee.PayMethod);
            var payment = strategy.MakePayment(employee, DateTime.Now.Month, DateTime.Now.Year);

            EmployeeIndexViewModel model = new EmployeeIndexViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentUser, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel

                Employee = employee,
                Today = todayEvent,
                Tomorrow = tomorrowEvent,
                TotalPay = payment.TotalPay,
            };

            return View(model);
        }
    }
}

Views/Views/Shared/_Admin.cshtml
@model Entities.ViewModels.BaseViewModel
<!DOCTYPE html>
<html  lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - HORIZON</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="d-flex" id="wrapper">
        <div class="bg-light" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <div class="nav navbar-header m-3 ml-4">
                    <img src="@Url.Content(Model.LogoUrl)" width="130" height="130" alt="No image available" style="border-radius:25px;border:solid 0.1px;" />
                </div>
            </div>
            <div id="sidebar-items" class="list-group">
                <ul class="nav flex-column  ml-4 mt-2 mr-0">
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "Admin")" title="Home Page">
                            <i class="fa fa-home"></i>
                            <span>
                                <strong class="ml-2">Home</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "AdminEvent")" title="Employee Schedule">
                            <i class="fa fa-calendar-minus-o"></i>
                            <span>
                                <strong class="ml-2">Calendar</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "AdminDashboard")" title="Company News">
                            <i class="fa fa-newspaper-o"></i>
                            <span>
                                <strong class="ml-2">Dashboard</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "AdminDetails")" title="Details">
                            <i class="fa fa-user-circle-o"></i>
                            <span>
                                <strong class="ml-2">Details</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "AdminStatistics")" title="Company Statistics">
                            <i class="fa fa-bar-chart"></i>
                            <span>
                                <strong class="ml-2">Statistics</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "AdminRequest")" title="Employee Requests">
                            <i class="fa fa-comment-o"></i>
                            <span>
                                <strong class="ml-2">Request</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "AdminSubscription")" title="Upgrade Account">
                            <i class="fa fa-credit-card"></i>
                            <span>
                                <strong class="ml-2">Subscription</strong>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="page-content-wrapper">
            <header>
                @Html.Partial("_LogoutPartial")
            </header>
            <div></div>
            <!-- /#page-content-wrapper -->
            <div class="container-fluid">

                <div class="justify-content-center">
                    @Html.Partial("_Messages")
                </div>
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            icon = $(this).find("i");
            icon.toggleClass("fa-arrow-circle-right fa-arrow-circle-left")
        });
    </script>
</body>
</html>

Views/Views/Shared/_Employee.cshtml
@model Entities.ViewModels.BaseViewModel
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title - HORIZON</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="d-flex" id="wrapper">
        <div class="bg-light" id="sidebar-wrapper">
            <div class="sidebar-heading">
                <div class="nav navbar-header m-3 ml-4">
                    <img src="@Url.Content(Model.LogoUrl)" width="130" height="130" alt="No image available" style="border-radius:25px;border:solid 0.1px;" />
                </div>
            </div>
            <div id="sidebar-items" class="list-group">
                <ul class="nav flex-column  ml-4 mt-2 mr-0">
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "Employee")" title="Home Page">
                            <i class="fa fa-home"></i>
                            <span>
                                <strong class="ml-2">Home</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "EmployeeSchedule")" title="Employee Schedule">
                            <i class="fa fa-calendar-minus-o"></i>
                            <span>
                                <strong class="ml-2">Calendar</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "EmployeeDashboard")" title="Company News">
                            <i class="fa fa-newspaper-o"></i>
                            <span>
                                <strong class="ml-2">Dashboard</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "EmployeeDetails")" title="Details">
                            <i class="fa fa-user-circle-o"></i>
                            <span>
                                <strong class="ml-2">Details</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "EmployeePayment")" title="Payments">
                            <i class="fa fa-money"></i>
                            <span>
                                <strong class="ml-2">Payments</strong>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item m-3">
                        <a href="@Url.Action("Index", "EmployeeRequest")" title="Employee Requests">
                            <i class="fa fa-comment-o"></i>
                            <span>
                                <strong class="ml-2">Request</strong>
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="page-content-wrapper">
            <header>
                @Html.Partial("_LogoutPartial")
            </header>
            <!-- /#page-content-wrapper -->
            <div class="container-fluid">
                <div class="justify-content-center">
                    @Html.Partial("_Messages")
                </div>
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
            icon = $(this).find("i");
            icon.toggleClass("fa-arrow-circle-right fa-arrow-circle-left")
        });
    </script>
</body>
</html>

Views/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - HORIZON</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Views/Shared/_Login.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/FrontContent/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="bg-image" style="background-image: url('../../Content/img/sky2.jpg')"></div>
    <div class="container body-content">
        <div class="col-md-12 pr-0 pl-0">
            @RenderBody()
        </div>
    </div>
    <footer class="footer fixed-bottom">
        <p>&copy; HORIZON 2021</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Views/Shared/_LogoutPartial.cshtml
@model Entities.ViewModels.BaseViewModel
<nav id="topnavbar" class="navbar navbar-expand-lg navbar-light bg-light border-bottom text-nowrap">

    <button class="btn" id="menu-toggle"><i class="fa fa-arrow-circle-left"></i></button>

    <button id="tglbtn" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <span class="nav-item justify-content-start ml-2" id="navcomp">
        @if (Request.IsAuthenticated)
        {
            @Html.DisplayFor(m => m.LoggedCompany)
        }
        else
        {
            @Html.Label("ERP")
        }
    </span>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item" id="navdate">
                    @Model.DateNow
            </li>
            @if (Request.IsAuthenticated)
            {
                <li id="lgtbtn" class="nav-item">
                    @using (Html.BeginForm("LogOff", "Home", new { id = "logoutForm" }, FormMethod.Post))
                    {
                        @Html.DisplayFor(m => m.LoggedUser)
                        @Html.AntiForgeryToken()
                        <button title="Log off" type="submit" value="Log Off" class="btn">
                            <i class="fa fa-sign-out"></i>
                        </button>
                    }
                </li>
            }
            else
            {
                <li class="nav-item">
                    @Html.ActionLink("Log out", "Login", "Home", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "btn btn-link nav-link text-white" })
                </li>
            }
        </ul>
    </div>
</nav>

Views/Views/Shared/_Messages.cshtml
@model Entities.ViewModels.BaseViewModel

@if (!string.IsNullOrEmpty(@Model.Message))
{
    <div id="AutoHide" class="col-md-2">
        @Model.Message
    </div>
}