Views/Controllers/EmployeePaymentController.cs
using Entities.EmployeeViewModels;
using Entities.Models;
using Entities.ViewModels;
using Repositories.Services;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Views.Controllers.BaseControllers;

namespace Views.Controllers
{
    public class EmployeePaymentController : BaseEmployeeController
    {
        // GET: EmployeePayment
        public async Task<ActionResult> Index(int? paymentsYear)
        {
            int filteredYear = paymentsYear ?? DateTime.Now.Year;
            var user = await _employeeRepository.GetEmployeeWithPaymentsAsync(CurrentUser) ?? new EmployeeUser() { Payments = new List<Payment>() };
            var years = user.Payments.Select(p => p.Year).Distinct();
            var filteredPayments = user.Payments.Where(p => p.Year == filteredYear);
            Payment[] payments = YearPaymentsService.YearPaymentsByMonth(filteredPayments);

            EmloyeePaymentsViewModel model = new EmloyeePaymentsViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentUser, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel

                PaymentsYear = filteredYear,
                Year = years.ToList(),
                Payments = payments,
                Employee = user,
                MonthNames = CultureInfo.CreateSpecificCulture("en-GB").DateTimeFormat.MonthNames
            };

            return View(model);
        }


        public async Task<ActionResult> ViewPayment(int paymentId) 
        {
            var user = await _employeeRepository.GetEmployeeWithPaymentsAsync(CurrentUser);
            var payment = user.Payments.FirstOrDefault(p => p.PaymentId == paymentId);
            var company = _companyRepository.GetCompany(CurrentCompanyId);
            var yearToDate = await new YearToDateService(_employeeRepository).CalculateYearToDate(CurrentUser, payment.Month);

            PaymentViewModel model = new PaymentViewModel
            {
                LoggedCompany = CurrentCompany, //BaseViewModel
                LoggedUser = CurrentUser, //BaseViewModel
                LogoUrl = CurrentLogoUrl, //BaseViewModel
                 
                Company = company,
                Employee = user,
                Payment = payment,
                YearToDate = yearToDate             
            };

            return View(model);
        }
    }
}

Views/Views/EmployeePayment/Index.cshtml
@model Entities.EmployeeViewModels.EmloyeePaymentsViewModel
@{
    Layout = "~/Views/Shared/_Employee.cshtml";
    ViewBag.Title = "Payments";
    int index = 0;
}

<div class="h1 mt-5 ml-3">@ViewBag.Title</div>
<div class="ml-3">Yearly payments overview</div>
<hr />

<div class="row mt-3 mb-3 ml-5">

    <div class="h3 m-4">Employee @Model.Employee.FullName payments for year @Model.PaymentsYear</div>
    @if (Model.Year.Count() > 1)
    {
        using (Html.BeginForm("Index", "EmployeePayment", FormMethod.Get, new { @class = "form-inline float-right" }))
        {
            @Html.DropDownListFor(m => m.PaymentsYear, new SelectList(Model.Year), new { @id = "btnUpdate", @class = "btn ml-3", @style = "height:40px;" })
        }
    }
</div>

<div class="container-fluid">
    <div class="col-md-12 mt-0 mr-5 ml-5">
        @for (int i = 1; i < 4; i++)
        {
            <div class="row">
                @for (int j = 1; j < 5; j++)
                {
                    index++;

                    if (Model.Payments[index].PaymentId == 0)
                    {
                        <a class="btn update col-md-2 m-4 p-0" style="height:100px;">
                            <p class="requestColor" style="border-radius:20px 20px 0px 0px;">@Model.MonthNames[index - 1]</p>
                            <p class="mt-2">No Payment</p>
                        </a>
                    }
                    else
                    {
                        <a href="@Url.Action("ViewPayment", "EmployeePayment", new { paymentId = Model.Payments[index].PaymentId })" class="btn update col-md-2 m-4 p-0" style="height:100px;">
                            <p class="requestColor" style="border-radius:20px 20px 0px 0px;">@Model.MonthNames[index - 1]</p>
                            <p class="mt-2">@Model.Payments[index].TotalPay <span>&euro;</span></p>
                            <div>
                                <i class="fa fa-pencil"></i>
                                <span>
                                    <strong>Payslip</strong>
                                </span>
                            </div>
                        </a>
                    }

                }
            </div>
        }
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#btnUpdate").change(function () {
                $("form").submit();
            });
        });
    </script>
}

Views/Views/EmployeePayment/ViewPayment.cshtml
@model Entities.ViewModels.PaymentViewModel
@{
    Layout = "~/Views/Shared/_Employee.cshtml";
    decimal netTotalPay = Model.Payment.TotalPay - Model.Payment.TaxPay;
    decimal netTotalPayYTD = Model.YearToDate.TotalPayYTD - Model.YearToDate.TaxPayYTD;
}
<div id="btnDiv" class="mt-2">
    @Html.ActionLink("return", "Index", "EmployeePayment", "", new { @class = "btn m-2" })
    <input id="printBtn" type="button" class="btn m-2" value="Print" />
    <hr />
</div>

<div class="container fa-border" id="payslip">
    <div class="row m-2">
        <div class="col-md-1">
            <img src="@Url.Content(Model.Company.LogoUrl ?? "~/CompanyLogo/Default.jpg")" width="100" height="100" alt="No image available" style="border-radius:25px;border:solid 0.1px;" />
        </div>
        <div class="col-md-9">
            <div class="container">
                <h2 class="ml-3" style="color:#2c6297;font-size:36px;font-weight:bolder;">@Model.Company.CompanyName</h2>
                <p class="ml-3">Address: @Model.Company.CompanyAddress</p>
                <p class="ml-3">Phone: @Model.Company.CompanyPhone</p>
            </div>
        </div>
        <div class="col-md-2">
            <p class="text-right mr-3" style="color:#2c6297;font-size:36px;font-weight:bolder;">PAYSLIP</p>
        </div>
    </div>
    <div class="row mt-4 ml-2 mr-2">
        <div class="col-md-3">
            <h2 style="background-color:#2c6297;color:white">EMPLOYEE INFORMATION</h2>
            <p>@Model.Employee.FullName</p>
            <p>Address: @Model.Employee.Address</p>
            <p>Phone: @Model.Employee.PhoneNumber</p>
        </div>
        <div class="col-md-4 offset-5">
            <table class="table table-borderless text-center">
                <thead style="background-color:#2c6297;color:white">
                    <tr>
                        <th>PAY DATE</th>
                        <th>PAY TYPE</th>
                        <th>PERIOD </th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="background-color:#7e909a;color:#f1f1f1">
                        <td>@Model.Payment.PayDate.Value.ToShortDateString()</td>
                        <td>@Model.Employee.PayMethod</td>
                        <td>@Model.Payment.PayDate.Value.Month</td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-hover table-borderless text-center">
                <thead style="background-color:#2c6297;color:white">
                    <tr>
                        <th colspan="2">EMPLOYEE ID</th>
                        <th>TAX RATE</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="background-color:#7e909a;color:white">
                        <td colspan="2">@Model.Employee.UserName</td>
                        <td>@Model.Employee.TaxRate %</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-5 mr-2 ml-2 mb-5">
        <div class="col-md-12">
            <table class="table table-borderless">
                <thead style="background-color:#2c6297;color:white">
                    <tr>
                        <th class="text-left" width="20%">EARNINGS</th>
                        <th class="text-left" width="20%">HOURS</th>
                        <th class="text-center" width="20%">RATE</th>
                        <th class="text-right" width="20%">CURRENT</th>
                        <th class="text-right" width="20%">YTD</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="text-left">Standard Pay</td>
                        <td class="text-left">@Model.Payment.WorkHours</td>
                        <td class="text-center">@Model.Employee.PayRate</td>
                        <td class="text-right">@Model.Payment.NormalPay</td>
                        <td class="text-right">@Model.YearToDate.NormalPayYTD</td>
                    </tr>
                    <tr>
                        <td class="text-left">Overtime Pay</td>
                        <td class="text-left">@Model.Payment.OverTimeHours</td>
                        <td class="text-center">@Model.Employee.OverTimeRate</td>
                        <td class="text-right">@Model.Payment.OverTimePay</td>
                        <td class="text-right">@Model.YearToDate.OverTimePayYTD</td>
                    </tr>
                    <tr>
                        <td class="text-left">Holiday Pay</td>
                        <td class="text-left">@Model.Payment.HolidayHours</td>
                        <td class="text-center">@Model.Employee.PayRate</td>
                        <td class="text-right">@Model.Payment.HolidayPay</td>
                        <td class="text-right">@Model.YearToDate.HolidayPayYTD</td>
                    </tr>
                    <tr>
                        <td class="text-right" colspan="5">-</td>
                    </tr>
                    <tr>
                        <td class="text-right" colspan="5">-</td>
                    </tr>
                    <tr style="background-color:#7e909a;color:white">
                        <td class="text-left" colspan="3">GROSS PAY</td>
                        <td class="text-right">@Model.Payment.TotalPay</td>
                        <td class="text-right">@Model.YearToDate.TotalPayYTD</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row mt-5 mr-2 ml-2 mb-5">
        <div class="col-md-12">
            <table class="table table-borderless">
                <thead style="background-color:#2c6297;color:white">
                    <tr>
                        <th class="text-left" width="20%">DEDUCTIONS</th>
                        <th class="text-left" width="20%"></th>
                        <th class="text-left" width="20%"></th>
                        <th class="text-right" width="20%">CURRENT</th>
                        <th class="text-right" width="20%">YTD</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="background-color:#7e909a;color:white">
                        <td class="text-left" colspan="3" width="60%">Tax Pay</td>
                        <td class="text-right" width="20%">@Model.Payment.TaxPay</td>
                        <td class="text-right" width="20%">@Model.YearToDate.TaxPayYTD</td>
                    </tr>
                    <tr>
                        <td class="text-right" colspan="5">-</td>
                    </tr>
                    <tr>
                        <td class="text-right" colspan="5">-</td>
                    </tr>
                    <tr style="background-color:#7e909a;color:white">
                        <td class="text-left" width="60%" colspan="3">NET PAY</td>
                        <td class="text-right" width="20%">@netTotalPay</td>
                        <td class="text-right" width="20%">@netTotalPayYTD</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


@section Scripts{
    <script>
        $(document).ready(function () {

            function TogglePrint() {
                $("#wrapper").toggleClass("toggled");
                icon = $("#menu-toggle").find("i");
                icon.toggleClass("fa-arrow-circle-right fa-arrow-circle-left")
                $("#btnDiv").toggle();
            }

            $("#printBtn").click(function () {
                TogglePrint();              
                window.print();
                TogglePrint();
            })
        })
    </script>
}